name = "planet-funksprueche"
main = "src.js"
compatibility_date = "2026-09-01"

[vars]
ALLOWED_ORIGIN = "https://planetsmashburger.de"
SITE_HOSTNAME = "planetsmashburger.de"
NEWSLETTER_SEGMENT_ID = "1f286196-516a-43ac-90e4-806694593c0d"

[[d1_databases]]
binding = "DB"
database_name = "planet-funksprueche"
database_id = "655926ba-176b-440a-9287-abd840cb78a5"
